### ISSUE TITLE
Open Session file results in VAPOR quit.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1472]
Platform: MacOS (Didn't test others.)

Steps:
1. Open VAPOR
2. Import a CF compliant file. 
3. Create a Volume renderer.
4. Save a session file.
4. Close VAPOR.
5. Open VAPOR.
4. Try to open the session file that's just saved.
3. VAPOR quits.

**Comment by shaomeng** [comment]
@leighorf also reports the same behavior on Linux, with this information:

fuggle: /home/orf/vapor3b/VAPOR3-3.1.0.RC0-Linux/bin ./vapor
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)

When run with gdb a little more info comes forth:

(gdb) where
#0  0x00007ffff1fb6207 in raise () from /lib64/libc.so.6
#1  0x00007ffff1fb78f8 in abort () from /lib64/libc.so.6
#2  0x00007ffff28c57d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007ffff28c3746 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff28c3773 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff28c39e9 in __cxa_rethrow () from /lib64/libstdc++.so.6
#6  0x00007ffff61cd0d6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/orf/vapor3b/VAPOR3-3.1.0.RC0-Linux/lib/libQtCore.so.4
#7  0x00007ffff61d1e89 in QCoreApplication::exec() () from /home/orf/vapor3b/VAPOR3-3.1.0.RC0-Linux/lib/libQtCore.so.4
#8  0x00000000004663f8 in main ()
