### ISSUE TITLE
Flow: No unsteady trajectories

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1846]
On OSX, using the DUKU WRF dataset, found at the path below on glade:

/glade/p/cisl/vast/vapor/data/VDC/vapor-3.0.0/WRF/DUKU/DUKU-3.0.0.nc

1) Create a Flow renderer and enable it
2) Enable unsteady flow
3) Set the non-random rake

I observe no streamlines with the above settings.  Adding more streamlines to the X, Y, or Z distribution has no effect either.  

![Screen Shot 2019-09-05 at 4 17 31 PM](https://user-images.githubusercontent.com/9522770/64387315-d1c99980-cff8-11e9-8464-f2bb300e18b8.png)

**Comment by shaomeng** [comment]
Note on 9/10/2019: it does show flow lines when the time step is non-zero. However, there's a crash seemingly related to the data manager. Below is the gdb output:

````
Thread 1 "vapor" received signal SIGSEGV, Segmentation fault.
0x00007ffff5115beb in VAPoR::QuadTreeRectangle<float, unsigned long>::GetPayloadContained (
    this=0xb3f4d80, x=-512149.312, y=4118692.75, payloads=std::vector of length 0, capacity 0)
    at /home/shaomeng/Git/VAPOR-flow-src/include/vapor/QuadTreeRectangle.hpp:138
138		const node_t *root = _nodes[_rootidx];
(gdb) bt
#0  0x00007ffff5115beb in VAPoR::QuadTreeRectangle<float, unsigned long>::GetPayloadContained (
    this=0xb3f4d80, x=-512149.312, y=4118692.75, payloads=std::vector of length 0, capacity 0)
    at /home/shaomeng/Git/VAPOR-flow-src/include/vapor/QuadTreeRectangle.hpp:138
#1  0x00007ffff5114a52 in VAPoR::CurvilinearGrid::_insideGrid (this=0xb601fc0, x=-512149.3125, 
    y=4118692.75, z=4635.3349609375, i=@0x7fffffffc950: 0, j=@0x7fffffffc958: 0, 
    k=@0x7fffffffc960: 0, lambda=0x7fffffffc9b0, zwgt=0x7fffffffc9a0)
    at /home/shaomeng/Git/VAPOR-flow-src/lib/vdc/CurvilinearGrid.cpp:991
#2  0x00007ffff5111836 in VAPoR::CurvilinearGrid::InsideGrid (this=0xb601fc0, 
    coords=std::vector of length 3, capacity 3 = {...})
    at /home/shaomeng/Git/VAPOR-flow-src/lib/vdc/CurvilinearGrid.cpp:486
#3  0x00007ffff2d85ddb in flow::VaporField::InsideVolumeVelocity (this=0x71df038, 
    time=197078400, pos=...) at /home/shaomeng/Git/VAPOR-flow-src/lib/flow/VaporField.cpp:60
#4  0x00007ffff2d7de02 in flow::Advection::AdvectTillTime (this=0x71defd8, velocity=0x71df038, 
    deltaT=1080, targetT=197089200, method=flow::Advection::ADVECTION_METHOD::RK4)
    at /home/shaomeng/Git/VAPOR-flow-src/lib/flow/Advection.cpp:165
#5  0x00007ffff7623319 in VAPoR::FlowRenderer::_paintGL (this=0x71deec0, fast=false)
    at /home/shaomeng/Git/VAPOR-flow-src/lib/render/FlowRenderer.cpp:293
````

**Comment by shaomeng** [comment]
No longer observing this bug. Close until it comes out again.
