### ISSUE TITLE
Ubuntu crashing on 3.4.0 preRelease

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2652]
Ubuntu's CircleCI build is referencing an older version of our third party libraries, which is causing it to crash upon opening data.  A fix is on the way.

cc @shaomeng

**Comment by shaomeng** [comment]
Don't know if this is the same message on your test, but I see this:

```
shaomeng@cisl-vapor:VAPOR3-3.4.0-Linux$ ./bin/vapor ~/cm1.nc 
Failed to import the site module
Traceback (most recent call last):
  File "/home/shaomeng/Downloads/VAPOR3-3.4.0-Linux/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/home/shaomeng/Downloads/VAPOR3-3.4.0-Linux/lib/python3.6/site.py", line 540, in main
    known_paths = addsitepackages(known_paths)
  File "/home/shaomeng/Downloads/VAPOR3-3.4.0-Linux/lib/python3.6/site.py", line 328, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/shaomeng/Downloads/VAPOR3-3.4.0-Linux/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/shaomeng/Downloads/VAPOR3-3.4.0-Linux/lib/python3.6/site.py", line 163, in addpackage
    for n, line in enumerate(f):
  File "/home/shaomeng/Downloads/VAPOR3-3.4.0-Linux/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 37: invalid start byte
```

**Comment by sgpearse** [comment]
This is fixed with the [current installer](https://github.com/NCAR/VAPOR/releases/download/3.4_PreRelease/VAPOR3-3.4.0-Ubuntu18-22_03_21-17.13.sh) on our pre-release page.

This fix involved rewriting the python library in our 3rd party tarball.  Since there have been no changes to our master branch for this fix, I've run the platform tests for Ubuntu 18 and 20 and they all pass.

This update is showing some new limitations in DockerHub (which CircleCI uses to reference its OS instance), which we can discuss tomorrow.  I suggest they be addressed after the release.
