### ISSUE TITLE
Can't import vapor after building and installing conda image

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3194]
I'm building vapor_python on my mac with:

```
cd vapor/conda
conda build .
conda install /Users/clyne/tmp/miniconda/envs/xarray/conda-bld/osx-64/vapor-3.6.0-ha5a8b8e_0.tar.bz2
```

The installation appears successful:

```
(xarray) bash-5.1$ conda list | grep vapor
vapor                     3.6.0                ha5a8b8e_0    file:///Users/clyne/tmp/miniconda/envs/xarray/conda-bld
```

But when I try to import vapor I get:

```
import vapor
cling::DynamicLibraryManager::loadLibrary() [/Users/clyne/tmp/miniconda/envs/xarray/lib/libvapi.dylib -> /Users/clyne/tmp/miniconda/envs/xarray/lib/libvapi.dylib]: dlopen(/Users/clyne/tmp/miniconda/envs/xarray/lib/libvapi.dylib, 9): Library not loaded: @rpath/libgeotiff.5.dylib
  Referenced from: /Users/Shared/tmp/miniconda/envs/xarray/lib/librender.dylib
  Reason: image not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/clyne/tmp/miniconda/envs/xarray/lib/python3.9/site-packages/vapor/__init__.py", line 1, in <module>
    from . import link
  File "/Users/clyne/tmp/miniconda/envs/xarray/lib/python3.9/site-packages/vapor/link.py", line 13, in <module>
    cppyy.load_library('vapi')
  File "/Users/clyne/tmp/miniconda/envs/xarray/lib/python3.9/site-packages/cppyy/__init__.py", line 237, in load_library
    raise RuntimeError('Unable to load library "%s"%s' % (name, err.err))
RuntimeError: Unable to load library "libvapi"
```

**Comment by clyne** [comment]
Quick update: Same results on casper:

```
>>> import vapor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/glade/u/home/clyne/.conda/envs/vapor_python/lib/python3.9/site-packages/vapor/__init__.py", line 1, in <module>
    from . import link
  File "/glade/u/home/clyne/.conda/envs/vapor_python/lib/python3.9/site-packages/vapor/link.py", line 13, in <module>
    cppyy.load_library('vapi')
  File "/glade/u/home/clyne/.conda/envs/vapor_python/lib/python3.9/site-packages/cppyy/__init__.py", line 255, in load_library
    raise RuntimeError('Unable to load library "%s"%s' % (name, err.err))
RuntimeError: Unable to load library "libvapi"
cling::DynamicLibraryManager::loadLibrary() [/glade/u/home/clyne/.conda/envs/vapor_python/lib/libvapi.so -> /glade/u/home/clyne/.conda/envs/vapor_python/lib/libvapi.so]: libassimp.so.5: cannot open shared object file: No such file or directory
```

**Comment by sgpearse** [comment]
Steps to install conda bundles:
https://docs.google.com/document/d/1RvbnJ_LbWvlUZzgjeutLQKwJV_M0blEHFSxsgSB7wRQ/edit#heading=h.jdi94x911txd

**Comment by clyne** [comment]
Closing this. Operator error. The document linked above has been revised with more complete information for building and installing a conda image.
