### ISSUE TITLE
Linux conda installers fail on certain machines

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3208]
The Linux conda installers are showing incompatibilities between different machines due to a file permissions issue.  This occurs in the `(Re-)building pre-compiled headers` step just after installation.  It appears to be trying to access an intermediate directory used when the installer was built.  Of course, this directory does not exist except on the original build system.

`PermissionError: [Errno 13] Permission denied: '/root/miniconda/conda-bld/vapor_1661792582084/work'`

The CircleCI/Ubuntu build **does** work on Casper, so we can proceed with release testing.

However, I'm seeing the error for installers generated according to [these instructions](https://docs.google.com/document/d/1RvbnJ_LbWvlUZzgjeutLQKwJV_M0blEHFSxsgSB7wRQ/edit#), with the configurations below.  Available installers are linked as appropriate.

| Build system | Test system | Build type |
| --- | --- | --- |
| Casper | Tower/Centos | Release |
| [CircleCI/Centos ](https://app.circleci.com/pipelines/github/NCAR/VAPOR/6037/workflows/e154c4b2-09fe-4a10-aab6-e36639a33c16/jobs/14456/artifacts) | Casper | Release |
| [CircleCI/Centos](https://app.circleci.com/pipelines/github/NCAR/VAPOR/6037/workflows/e154c4b2-09fe-4a10-aab6-e36639a33c16/jobs/14456/artifacts) | Tower/Centos | Release |
| [CircleCI/Ubuntu](https://app.circleci.com/pipelines/github/NCAR/VAPOR/6038/workflows/28121f21-f064-4bfe-a003-dca6b17fdac7/jobs/14461/artifacts) | Tower/Ubuntu | Release |
| Tower/Centos | Casper | Release |
| Tower/Ubuntu | Casper | Release |

Full error report from CentOS builds:
```
>>> from vapor import *
(Re-)building pre-compiled headers (options: -O2 -mavx); this may take a minute ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/glade/work/pearse/conda-envs/vapor/lib/python3.9/site-packages/vapor/__init__.py", line 1, in <module>
    from . import link
  File "/glade/work/pearse/conda-envs/vapor/lib/python3.9/site-packages/vapor/link.py", line 2, in <module>
    from . import config
  File "/glade/work/pearse/conda-envs/vapor/lib/python3.9/site-packages/vapor/config.py", line 35, in <module>
    roots = [*roots]
  File "/glade/work/pearse/conda-envs/vapor/lib/python3.9/pathlib.py", line 1414, in exists
    self.stat()
  File "/glade/work/pearse/conda-envs/vapor/lib/python3.9/pathlib.py", line 1222, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/miniconda/conda-bld/vapor_1661792582084/work'
```

Full error report from Ubuntu builds:
```
(vapor) vapor2@vapor2:~$ python
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapor
(Re-)building pre-compiled headers (options: -O2 -mavx); this may take a minute ...
Vapor 3.6.1
Python 3.9.5 (/home/vapor2/anaconda3/envs/vapor)
 *** Break *** segmentation violation
 *** Break *** segmentation violation
```

**Comment by sgpearse** [comment]
We will keep this open for now.  Our .tar.bz packages that build on conda's Docker image install well on all platforms, but our builds that are based off of the CentOS build fail.  If CondaForge bases their build off of Conda, our builds may fail as well, so let's keep it open until we are in the clear.

**Comment by sgpearse** [comment]
Fixed
