### ISSUE TITLE
Manually built Python API installers do not work on CentOS

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3299]
As of 863fe83, the Python API .tar.bz2 installers built on CircleCI error on CentOS after importing vapor.  Errors below:

Casper:
```
(vaporManual) -bash-4.2$ python
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03) 
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapor
(Re-)building pre-compiled headers (options: -O2 -mavx); this may take a minute ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/glade/work/pearse/conda-envs/vaporManual/lib/python3.9/site-packages/vapor/__init__.py", line 1, in <module>
    from . import link
  File "/glade/work/pearse/conda-envs/vaporManual/lib/python3.9/site-packages/vapor/link.py", line 13, in <module>
    cppyy.load_library('vapi')
  File "/glade/work/pearse/conda-envs/vaporManual/lib/python3.9/site-packages/cppyy/__init__.py", line 255, in load_library
    raise RuntimeError('Unable to load library "%s"%s' % (name, err.err))
RuntimeError: Unable to load library "libvapi"
>>> import sys
>>> sys.path()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'list' object is not callable
>>> sys.path
['', '/glade/work/pearse/conda-envs/vaporManual/lib/python39.zip', '/glade/work/pearse/conda-envs/vaporManual/lib/python3.9', '/glade/work/pearse/conda-envs/vaporManual/lib/python3.9/lib-dynload', '/glade/work/pearse/conda-envs/vaporManual/lib/python3.9/site-packages']`
```

Test tower error, running CentOS:

```
"(vaporManual) [vapor2@localhost ~]$ conda install -c file:///home/vapor2/channel/ vapor
Collecting package metadata (current_repodata.json): done                                                      
Solving environment: failed with initial frozen solve. Retrying with flexible solve.                           
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0

Your installed version is: 2.17"
```

**Comment by sgpearse** [comment]
Closing as we no longer directly support CentOS and the API is passing tests on other Linux platforms.

**Comment by sgpearse** [comment]
Closing as the API is passing tests on all other Linux platforms.
